twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        global_view_link: '<span class="fa fa-eye"></span>'
        global_edit_link: '<span class="fa fa-pencil"></span>'
        global_columnizer: "@App\\Service\\Columnizer"

when@test:
    twig:
        strict_variables: true
